name: Node Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # This line enables npm's built-in caching mechanism

    - name: Check for package-lock.json
      run: |
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found, running npm install to generate one"
          npm install
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add package-lock.json
          git commit -m "Add generated package-lock.json"
          git push
        fi

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
      env:
        CI: true  # Ensures that npm test knows it's running in a CI environment

    - name: Build
      run: npm run build

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=avinash-nair_NodeCIExample
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
