name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Use stable Node.js versions that are actively supported

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # Include registry setup if you are using private packages
        # registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g npm@latest  # Ensure the latest npm is used

    - name: Check Versions
      run: |
        node -v
        npm -v

    - name: Run Tests
      run: npm test
      env:
        CI: true

    - name: Build
      run: npm run build

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=avinash-nair_NodeCIExample
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
