name: Node Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'  # Fetch all history to ensure all files are included

    - name: List directory contents
      run: |
        ls -la
        echo "Checking for package-lock.json:"
        if [ -f package-lock.json ]; then
          echo "package-lock.json is present"
        else
          echo "package-lock.json is missing"
        fi
        echo "Checking for yarn.lock:"
        if [ -f yarn.lock ]; then
          echo "yarn.lock is present"
        else
          echo "yarn.lock is missing"
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build
